Migrate kafka.
distributed-technologies/helm-charts pull request #139
Opened 2021-11-15 16:39 UTC by jacobcrawford

**Description of your changes:**
Migrate kafka to mono repo

Checklist:

* [ ] I have bumped the chart version
* [ ] I have documented my changes if this is needed
* [ ] I have described my changes in the "description of your changes" field
* [ ] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ ] I have created the necessary tests in the chart, if they are possible/necessary
* [ ] I have squashed commits if necessary

2021-11-15 19:22 UTC, skovbakke reviewed
The linting fails.

2021-11-15 19:22 UTC, skovbakke commented on charts/kafka/chart/Chart.yaml
> +version: v0.3.1
```suggestion
version: 0.3.1
```

2021-11-18 14:35 UTC, jaxels10 requested changes
1 comment

2021-11-18 14:35 UTC, jaxels10 commented on charts/kafka/chart/Chart.yaml
> +appVersion: "1.16.0"
Remove pl0x

2021-11-18 14:48 UTC, jaxels10 approved these changes
This looks okay to me. Jacob is vouching that it is okay that the helm install fails

2021-11-18 14:49 UTC, merged