Removed loadbalancer
distributed-technologies/helm-charts pull request #168
Opened 2021-12-01 12:25 UTC by jacobcrawford

**Description of your changes:**

Checklist:

* [ ] I have bumped the chart version
* [ ] I have documented my changes if this is needed
* [ ] I have described my changes in the "description of your changes" field
* [ ] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ ] I have created the necessary tests in the chart, if they are possible/necessary
* [ ] I have squashed commits if necessary

2022-01-10 10:47 UTC, jaxels10 requested changes
Some minor changes I have requested, Crawfoot

2022-01-10 10:47 UTC, jaxels10 commented on charts/kafka/chart/scripts/python_ksql.py
> +    print("Stream CREATED")
Why is one in upper case but the other was changed?

2022-01-10 10:47 UTC, jaxels10 commented on charts/kafka/chart/scripts/python_ksql.py
> +for i in range(30):
I love casual integers like this "30" where I have no clue what is going on.

2022-01-10 10:47 UTC, jaxels10 commented on charts/kafka/chart/scripts/python_ksql.py
> +    print("Table did not get data after 30 seconds")
I now see where the 30 came from

2022-01-10 10:47 UTC, jaxels10 commented on charts/kafka/chart/values.yaml
> +    resources:
This looks empty to me

2022-01-10 10:47 UTC, jaxels10 commented on charts/kafka/chart/values.yaml
> +    resources: {}
This looks less empty but still empty. Is this to overwrite the values in their values.yaml? If so, we should probably make it the same both places(so add {} above)

2022-01-12 14:40 UTC, klausenbusk commented on charts/artifact-registry/chart/templates/tests/cluster-role-binding.yaml
> +  name: test-pods
Can we just use the default `cluster-admin` or `view` role and avoid creating our own role?
```suggestion
  name: cluster-admin
```

2022-01-12 14:40 UTC, klausenbusk commented on charts/kafka/chart/templates/tests/test-kafka-ksql-pod.yaml
> +      imagePullPolicy: IfNotPresent
Downgrading to the last supported Python release is a bit odd (EOL in 1,5 year). Is it feasible to upgrade to Python 3.9 or 3.10?

2022-01-12 14:40 UTC, klausenbusk commented on charts/artifact-registry/chart/scripts/install_helm.sh
> +#!/bin/bash
We want to fail if any of the commands fail.
```suggestion
#!/bin/bash
set -e
```

2022-01-12 14:40 UTC, klausenbusk commented on charts/artifact-registry/chart/scripts/install_helm.sh
> +echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list
We don't need `tee`. `tee` is often used together with `sudo` to write to a file as non-root, but we aren't using `sudo` as we are already root.
```suggestion
echo "deb https://baltocdn.com/helm/stable/debian/ all main" > /etc/apt/sources.list.d/helm-stable-debian.list
```

2022-01-12 14:40 UTC, klausenbusk commented on charts/artifact-registry/chart/scripts/install_helm.sh
> +curl https://baltocdn.com/helm/signing.asc >> signing.asc
Just trusting a public key from *some* webserver is not the preferred way to do this. Ideally we would check the key fingerprint.

See some examples here: https://github.com/docker-library/official-images#image-build

This is only used for testing, so I'm not caring too much.

2022-01-12 19:12 UTC, jacobcrawford commented on charts/artifact-registry/chart/scripts/test_image_registry.sh
> +buildah pull alpine
Both Docker and podman need access to the CRI, which would require a whole lot more from within a container. buildah is just for building container images and therefore needs fewer privileges.

2022-01-12 19:27 UTC, jacobcrawford commented on charts/kafka/chart/values.yaml
> +      minimumInSyncReplicas: 1
Because we have to be able to test the default configuration. Having a default configuration of 3 replicas seems random and would make the tests run a lot slower.

2022-01-12 20:15 UTC, jacobcrawford commented on charts/kafka/chart/scripts/python_ksql.py
> +print("Connected")
![image](https://user-images.githubusercontent.com/22328547/149214810-409fbdc8-13dc-458f-9704-3739391a1713.png)
I guess the image used have python logging enabled

2022-01-12 20:54 UTC, jacobcrawford commented on charts/artifact-registry/chart/scripts/install_helm.sh
> +curl https://baltocdn.com/helm/signing.asc >> signing.asc
Since we are only testing I don't see a reason to change it here. But the comment is noted.

2022-01-14 12:44 UTC, jaxels10 commented on charts/kafka/chart/scripts/python_ksql.py
> +print("Connected")
Alright, thanks for clearing that up

2022-01-14 12:44 UTC, jaxels10 commented
Still a couple of comments left to answer and also a merge conflict still :)

2022-01-16 19:47 UTC, klausenbusk commented on charts/artifact-registry/chart/scripts/test_image_registry.sh
> +buildah pull alpine
I see. In that case I would prefer `skopeo` as we are already a bit familiar with it.

It is your call :)

2022-01-17 07:22 UTC, jacobcrawford commented on charts/kafka/chart/templates/tests/test-kafka-ksql-pod.yaml
> +      imagePullPolicy: IfNotPresent
I downgraded because of some unexpected behavior from the ksql library.  The latest version supported is 3.7

2022-01-18 12:44 UTC, klausenbusk approved these changes
LGTM 🎉

2022-01-18 15:42 UTC, klausenbusk approved these changes
LGTM 🎉

2022-01-21 06:59 UTC, jaxels10 approved these changes
LGTM

2022-01-21 10:15 UTC, jacobcrawford commented on .github/workflows/lint-and-test.yaml
> -        run: ct install --config ./.github/configs/ct-install.yaml
ct-lint and ct-install were not the same files, so I have added the ct-install again.

2022-01-21 11:54 UTC, jaxels10 approved these changes
With ct-install added, this LGTM

2022-01-21 13:29 UTC, klausenbusk approved these changes
LGTM 🎉

2022-01-21 13:30 UTC, merged