Feature/kafka ha
distributed-technologies/helm-charts pull request #223
Opened 2022-01-27 10:18 UTC by jacobcrawford

**Description of your changes:**

Checklist:

* [ ] I have bumped the chart version
* [ ] I have documented my changes if this is needed
* [ ] I have described my changes in the "description of your changes" field
* [ ] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ ] I have created the necessary tests in the chart, if they are possible/necessary
* [ ] I have squashed commits if necessary

2022-01-27 12:13 UTC, jacobcrawford commented
Without affinity:
![image](https://user-images.githubusercontent.com/22328547/151356650-82cfebfa-1e04-4d1c-82f7-56bd01a93879.png)

2022-01-27 12:51 UTC, jacobcrawford commented
With affinity:
![image](https://user-images.githubusercontent.com/22328547/151362430-85a5dfc8-9e14-4be3-8721-84076b689c1f.png)

2022-01-27 14:23 UTC, klausenbusk commented
Hmm, so no rolling update support on 3 nodes cluster?

2022-01-27 15:54 UTC, klausenbusk requested changes
I think the `matchLabels` syntax is easier to read, but looks good otherwise.

2022-01-27 15:54 UTC, klausenbusk commented on charts/kafka/chart/templates/kafka-operator.yaml
> +                        - kafka-zookeeper
The `matchLabels` syntax is a bit easier to read IMO:
```suggestion
                  matchLabels:
                    app: kafka-zookeeper
```

2022-01-27 15:54 UTC, klausenbusk commented on charts/kafka/chart/values.yaml
> +                    - cp-ksql-server
The `matchLabels` syntax is a bit easier to read IMO:
```suggestion
              matchLabels:
                app: cp-ksql-server
```

2022-01-27 15:54 UTC, klausenbusk commented on charts/kafka/chart/values.yaml
> +                    - cp-schema-registry
The `matchLabels` syntax is a bit easier to read IMO:
```suggestion
              matchLabels:
                app: cp-schema-registry
```

2022-01-27 15:54 UTC, klausenbusk commented on charts/kafka/chart/templates/kafka-operator.yaml
> +                        - kafka-broker
The `matchLabels` syntax is a bit easier to read IMO:
```suggestion
                  matchLabels:
                    app: kafka-broker
```

2022-01-28 03:51 UTC, skovbakke reviewed
Maybe we should be using a soft requirement? Or, is there a reason we need the hard one? 
e.g. https://github.com/distributed-technologies/helm-charts/pull/185

2022-01-28 03:51 UTC, skovbakke commented on charts/kafka/chart/templates/kafka-operator.yaml
> +            requiredDuringSchedulingIgnoredDuringExecution:
I think we should change this to a soft requirement. If there in some instance is fewer nodes than replicas we still want to schedule them.

2022-01-28 03:51 UTC, skovbakke commented on charts/kafka/chart/templates/kafka-operator.yaml
> +            requiredDuringSchedulingIgnoredDuringExecution:
Same as above.

2022-01-28 03:51 UTC, skovbakke commented on charts/kafka/chart/templates/kafka-operator.yaml
> +                        - kafka-broker
I agree

2022-01-28 03:51 UTC, skovbakke commented on charts/kafka/chart/values.yaml
> +        requiredDuringSchedulingIgnoredDuringExecution:
As for the broker/zookeeper.

2022-01-28 03:51 UTC, skovbakke commented on charts/kafka/chart/values.yaml
> +        requiredDuringSchedulingIgnoredDuringExecution:
as above.

2022-01-28 17:45 UTC, skovbakke commented on charts/kafka/chart/values.yaml
> +    replicaCount: 1
Why do we set this?

2022-01-31 07:51 UTC, jacobcrawford commented on charts/kafka/chart/values.yaml
> +    replicaCount: 1
This was a leftover from testing. It has been removed.

2022-01-31 08:32 UTC, jaxels10 reviewed
One comment we should discuss

2022-01-31 08:32 UTC, jaxels10 commented on charts/kafka/chart/templates/kafka-operator.yaml
> +              - weight: 100
Did we choose 100 based on anything?

2022-01-31 08:37 UTC, jaxels10 submitted a review, later dismissed
LGTM, remember to update the version since we have just merged a 1.0.1

2022-01-31 10:24 UTC, klausenbusk approved these changes
LGTM 🎉

2022-01-31 13:47 UTC, merged