Feature/topic configuration
distributed-technologies/helm-charts pull request #225
Opened 2022-01-28 12:15 UTC by jacobcrawford

**Description of your changes:**

Checklist:

* [ ] I have bumped the chart version
* [ ] I have documented my changes if this is needed
* [ ] I have described my changes in the "description of your changes" field
* [ ] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ ] I have created the necessary tests in the chart, if they are possible/necessary
* [ ] I have squashed commits if necessary

2022-01-28 12:28 UTC, jacobcrawford commented
Configs get propagated to KafkaTopic:
![image](https://user-images.githubusercontent.com/22328547/151546891-0e1a1b2c-045e-4a9b-a620-8b59548c2a5d.png)

2022-01-28 13:00 UTC, klausenbusk commented
Hmm, is having the version bump in a separate commit worth it? It basically just adds noise?

2022-01-28 17:49 UTC, skovbakke submitted a review, later dismissed
LGTM 🥳

2022-01-31 08:12 UTC, jaxels10 requested changes
Very very small changes. It generally looks good to me, although we should probably try to reduce whitespace in our templated files.

2022-01-31 08:12 UTC, jaxels10 commented on charts/kafka/chart/templates/kafka-topic-template.yaml
> +  {{ end }}
```suggestion
  {{- end }}
```
I know this is a small thing, but the templated files will look much better if we remove unnecessary white space

2022-01-31 08:12 UTC, jaxels10 commented on charts/kafka/chart/templates/kafka-topic-template.yaml
>  {{ end }}
```suggestion
{{- end }}
```

2022-01-31 08:22 UTC, jaxels10 approved these changes
LGTM

2022-01-31 09:35 UTC, merged