Feature/tempo
distributed-technologies/helm-charts pull request #245
Opened 2022-02-02 09:25 UTC by MadsHT

**Description of your changes:**

Checklist:

* [x] I have bumped the chart version
* [ ] I have documented my changes if this is needed
* [ ] I have described my changes in the "description of your changes" field
* [ ] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ ] I have created the necessary tests in the chart, if they are possible/necessary
* [ ] I have squashed commits if necessary

2022-02-03 03:31 UTC, skovbakke commented on .gitignore
> +charts/**/chart/charts/**.tgz
Could we just do this?
```suggestion
*.tgz
```

2022-02-03 08:03 UTC, MadsHT commented on .gitignore
> +charts/**/chart/charts/**.tgz
We could yes.

2022-02-09 13:01 UTC, skovbakke commented on charts/prometheus/chart/values.yaml
> +    enabled: false
Make sure there is a new-line at the end of the file.

2022-02-09 13:02 UTC, skovbakke commented on charts/tempo-distributed/chart/templates/bkt-claim.yaml
> +{{- end -}}
as above.

2022-02-09 13:06 UTC, skovbakke requested changes

2022-02-09 13:06 UTC, skovbakke commented on charts/tempo-distributed/chart/values.yaml
> +tempo-distributed:
We should not include verbatim values from the values file in the the dependency. Please only have the values that we set to something different that the default.

2022-02-10 07:19 UTC, MadsHT commented on charts/tempo-distributed/chart/values.yaml
> +tempo-distributed:
I have moved values for tempo out, but the values for the bucket claim should be in the values files since it's a template created by me

2022-02-10 10:38 UTC, skovbakke commented on charts/tempo-distributed/chart/values.yaml
> +tempo-distributed:
Now there is no values for tempo. Does it work with all default values?

2022-02-10 11:00 UTC, MadsHT commented on charts/tempo-distributed/chart/values.yaml
> +tempo-distributed:
It should work, it will just not use an s3 bucket fra Ceph, and use a local storage (I guess in memory).
The other values that I removed was setting different ports to deliver traces on, depending on the type it is, Jaeger, zipkin or otlp, and I suspect that it'll be nice to open and close these without having to building a new chart.
Same goes for enabling serviceMonitor and the searchable backend feature.

TL:DR
It should it will just use a local storage instaed of the ceph bucket.

2022-02-10 11:03 UTC, skovbakke approved these changes
LGTM, I have not done any testing though.

2022-02-10 13:36 UTC, MadsHT commented on charts/tempo-distributed/chart/values.yaml
> +bucketClaim:
Alright I will add it.

2022-02-10 13:36 UTC, MadsHT commented on charts/tempo-distributed/chart/values.yaml
> +  enabled: false
The ceph-bucket-claim resource is not deployed.

2022-02-10 13:38 UTC, jacobcrawford commented
I guess we also want to install the chart in our GitHub workflow. It can be done by adding the chart to this file: https://github.com/distributed-technologies/helm-charts/blob/main/.github/configs/ct-install.yaml

2022-02-10 13:42 UTC, MadsHT commented on charts/tempo-distributed/chart/values.yaml
> +bucketClaim:
Added to the bottom of the file, where the `tempo-distributed: ` obj starts

2022-02-11 08:02 UTC, skovbakke approved these changes
LGTM 😊

2022-02-11 11:48 UTC, jacobcrawford approved these changes
LGTM.

2022-02-14 11:17 UTC, merged