Helper ceph crd
distributed-technologies/helm-charts pull request #250
Opened 2022-02-17 08:13 UTC by MadsHT

**Description of your changes:**

Checklist:

* [ ] I have bumped the chart version
* [ ] I have documented my changes if this is needed
* [ ] I have described my changes in the "description of your changes" field
* [ ] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ ] I have created the necessary tests in the chart, if they are possible/necessary
* [ ] I have squashed commits if necessary

2022-02-17 09:27 UTC, skovbakke commented
Did you see I provided feedbach https://github.com/distributed-technologies/helm-charts/pull/246 ?

2022-02-17 09:29 UTC, MadsHT commented
I did not, I will have a look at them, thanks

2022-02-17 09:45 UTC, MadsHT commented
> Did you see I provided feedbach #246 ?

This pr has been updated with the feedbacj

2022-02-17 10:20 UTC, skovbakke commented on charts/helper-ceph-crd/chart/values.yaml
> +      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
Should this be placed on the template itself?
The issue, as I see it, with placing it in the values file, is that it can/will be overwritten as soon as someone wants to put another annotation when they use the template. Or is that the behavior we want? where it is optional?

2022-02-17 10:26 UTC, MadsHT commented on charts/helper-ceph-crd/chart/values.yaml
> +      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
That is true, I 'll move it back

2022-02-17 10:40 UTC, MadsHT commented on charts/helper-ceph-crd/chart/values.yaml
> +      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
Done

2022-02-17 10:54 UTC, jacobcrawford commented
I'm not sure how this chart should work in practice? Is it meant as a template chart that you can add as a dependency to your chart or is it meant to be deployed as a separate service along with the other charts in our service layer?

At the moment we have a policy of resources being created in the helm charts where they are used to not have strong coupling between charts.

2022-02-17 10:56 UTC, jacobcrawford requested changes
I think we need to expand the documentation on how to use this chart as a dependency chart, so that one should not need to read the code.

2022-02-17 12:46 UTC, MadsHT commented
> I think we need to expand the documentation on how to use this chart as a dependency chart, so that one should not need to read the code.

I have writen a README on what this chart does.
I will no try to tell you what each field does, but have instead referenced the actual resource documentation and the example in the values file.

2022-02-24 11:54 UTC, MadsHT commented
Bump

2022-02-24 12:07 UTC, klausenbusk commented on charts/helper-ceph-crd/README.md
> +There is currently only one hardcoded value that is applied to all the templates, the annotation `argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true`
You could explain what it does here :)

2022-02-24 12:07 UTC, klausenbusk commented on charts/helper-ceph-crd/README.md
> +The idear for this helper chart is that it will facilitate a way to make a storage in k8s where needed, this is why it also contains a storage-class resource.
Hmm, from reading that sentence, I'm not sure what this helper chart does. Something about storage in k8s.

Perhaps:
```suggestion
This helper chart facilitates creation of Ceph storage resources.
```

2022-02-24 12:29 UTC, MadsHT commented on charts/helper-ceph-crd/chart/templates/storage-class.yaml
> +{{- end }}
Well not really.. I just made a mistake in the `values.yaml` that I overlooked, that this solved.

I have added this and fixed my mistake in `values.yaml`

2022-02-24 12:31 UTC, MadsHT commented on charts/helper-ceph-crd/README.md
> +There is currently only one hardcoded value that is applied to all the templates, the annotation `argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true`
I am not sure what you want me to explain?

2022-02-24 12:32 UTC, MadsHT commented on charts/helper-ceph-crd/chart/templates/ceph-object-store.yaml
> +kind: CephObjectStore
You don't have to create one, this is just if the need arises, We can remove it if we feel it's unnecessary

2022-03-07 14:21 UTC, skovbakke commented on charts/helper-ceph-crd/README.md
> +There is currently only one hardcoded value that is applied to all the templates, the annotation `argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true`
I agree with Kristians comment. Add a line explaining why we have this hardcoded value, and perhaps with a link to the documentation of it.

2022-03-10 14:50 UTC, jacobcrawford commented
I'm wondering if this should actually be a helm [Library chart](https://helm.sh/docs/topics/library_charts/). Seems like this helper-chart is trying give us a DRY codebase, which is exactly what Library charts are for.

2022-03-11 08:28 UTC, MadsHT commented
> I'm wondering if this should actually be a helm [Library chart](https://helm.sh/docs/topics/library_charts/). Seems like this helper-chart is trying give us a DRY codebase, which is exactly what Library charts are for.

I personally do not think making this into a Library chart would add much value.

In my opinion, a library chart would "pollute" the proxy charts with templates, where this implementation allows resource generation without the need for templates.

2022-03-11 12:20 UTC, MadsHT commented
@jacobcrawford Do you find that your change request has been forfilled?

2022-03-14 08:17 UTC, jacobcrawford requested changes
Nothing needs to be added, but we should take remove some stuff for simplicity.

2022-03-14 08:17 UTC, jacobcrawford commented on charts/helper-ceph-crd/README.md
> +This is a helper chart that you use as a dependency on you main chart doing something like:
I think it is fair to assume that people know what a helm dependency is, and how to conditionally enable it.

2022-03-14 08:17 UTC, jacobcrawford commented on charts/helper-ceph-crd/README.md
> +Every resource that this chart helps with, is a list, so that it's plausible to make multiples of a resource if so desired, therefor if you wish to not create any resources, you will have to set the
The documentation from this point is great!

2022-03-14 08:25 UTC, MadsHT commented on charts/helper-ceph-crd/README.md
> +This is a helper chart that you use as a dependency on you main chart doing something like:
Updated

2022-08-24 08:31 UTC, closed without merging