Initial Kafka Topic replicator
distributed-technologies/helm-charts pull request #263
Opened 2022-02-25 09:42 UTC by jacobcrawford

**Description of your changes:**

This PR addresses the application part of a Kafka topics replicator. Infrastructure will come later. 

Checklist:

* [ ] I have bumped the chart version
* [ ] I have documented my changes if this is needed
* [ ] I have described my changes in the "description of your changes" field
* [ ] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ ] I have created the necessary tests in the chart, if they are possible/necessary
* [ ] I have squashed commits if necessary

2022-02-25 10:30 UTC, klausenbusk commented on charts/kafka-topic-replicator/container/requirements.txt
> +kafka_python==2.0.2
The Python ecosystem is moving away from `setuptools`. Modern Python projects use `pyproject.toml` (ex with [Poetry](https://python-poetry.org/), see [here](https://python-poetry.org/docs/basic-usage/) for basic usage), which IMO is a much nicer tool. Let's be modern!

2022-02-25 12:11 UTC, skovbakke commented on charts/kafka-topic-replicator/container/requirements.txt
> +kafka_python==2.0.2
Another alternative is [pipenv](https://github.com/pypa/pipenv).

2022-02-25 12:21 UTC, klausenbusk commented on charts/kafka-topic-replicator/container/tests/test_kafka_topic_replicator.py
> +import unittest
My Python friends recommends `pytest`, perhaps we should also recommend that? https://realpython.com/pytest-python-testing/#what-makes-pytest-so-useful

2022-02-25 12:37 UTC, jacobcrawford commented on charts/kafka-topic-replicator/container/requirements.txt
> +kafka_python==2.0.2
I get the comments but I think I'm missing the "why" of it all? 😄

2022-02-25 12:41 UTC, jacobcrawford commented on charts/kafka-topic-replicator/container/requirements.txt
> +kafka_python==2.0.2
Is it because we want to version the application? :)

2022-02-25 12:45 UTC, klausenbusk commented on charts/kafka-topic-replicator/container/requirements.txt
> +kafka_python==2.0.2
Because poetry is a better tool :) Ex: dependencies aren't installed globally but per project, so you know every developer is using exact same version of the dependency. The CLI is also very intuitive.

See ex: https://python-poetry.org/docs/basic-usage/

2022-02-25 12:51 UTC, jacobcrawford commented on charts/kafka-topic-replicator/container/tests/test_kafka_topic_replicator.py
> +import unittest
`pytest` is very simple, and team Singularity is already using it. I'm using `unitttest` to give another perspective on testing frameworks. `unittest` has a little more boiler plate and object oriented structure than `pytest`.

2022-02-25 12:52 UTC, klausenbusk commented on charts/kafka-topic-replicator/container/tests/test_kafka_topic_replicator.py
> +import unittest
That make sense :)

2022-02-25 13:23 UTC, jacobcrawford commented on charts/kafka-topic-replicator/container/requirements.txt
> +kafka_python==2.0.2
Let's separate the arguments:
1. What is wrong with the setup we have now?
2. What does the `pyproject.toml` file provide that we need?
3. Do we need Poetry for this setup or just `pyproject.toml`? 

I'm not familiar with the pyproject.toml file and it seems that it is not widely used yet. We need to think of the tradeoff between introducing something new and the value it provides.

2022-02-25 13:26 UTC, skovbakke requested changes
A few comments

2022-02-25 13:26 UTC, skovbakke commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +    return further_delay_ms/1000
I would prefer if we converted the the record timestamp to a datetime object and did the time arithmetic using python best practices with `timedelta`s. 
e.g. calculate the delay as
`record_datetime + datetime.timedelta(milliseconds=delay_ms) - datetime.now()`
and convert the result to seconds.

2022-02-25 13:26 UTC, skovbakke commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +def setupLogging():
Best practice in python is to use lowercase and underscores.
```suggestion
def setup_logging():
```

2022-02-25 13:28 UTC, skovbakke commented on charts/kafka-topic-replicator/container/requirements.txt
> +kafka_python==2.0.2
https://modelpredict.com/wht-requirements-txt-is-not-enough

2022-02-25 13:33 UTC, klausenbusk commented on charts/kafka-topic-replicator/container/requirements.txt
> +kafka_python==2.0.2
You asked for best-practices, so whatever you recommend is what people are gonna use :) So why not recommend modern tools? :)

> What is wrong with the setup we have now?

Dependencies are installed globally, which make it impossible (or at least difficult) to use different dependencies per project. Poetry supports this much more nicely.

> What does the pyproject.toml file provide that we need?

Better tools. The Python ecosystem is moving away from `setuptools` and `pyproject.toml` is the future.

2022-02-27 12:49 UTC, jaxels10 reviewed
A comment about integer values :)

2022-02-27 12:49 UTC, jaxels10 commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +    return int(datetime.now().timestamp() * 1000)
Integer values should perhaps be defined with a name. It will be more readable. Perhaps with an enum or a global variable that is immutable.

2022-02-27 13:06 UTC, klausenbusk commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +def createConsumer(kafka_broker_endpoint,input_topic):
Consider adding type hints.

https://lyz-code.github.io/blue-book/coding/python/type_hints/

https://www.python.org/dev/peps/pep-0484/

2022-02-28 09:30 UTC, jacobcrawford commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +        log.exception(e)
First I agree that one should try to catch as specific exceptions as possible. In this case, the documentation does not state which exceptions are thrown from the constructor, which makes it super hard to be specific at all. 
Second I think we want the application to exit, so we should just propagate the exception. In this case, we might actually just want to remove the try, except or the whole wrapper?

2022-02-28 09:46 UTC, jacobcrawford commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +        log.exception(e)
I actually think the wrapper should stay so that the methods are easily mocked.

2022-02-28 11:23 UTC, skovbakke commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +            group_id=f'delay-{input_topic}')
There is some inconsistency between these two return statements.

2022-02-28 13:13 UTC, jacobcrawford commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +            group_id=f'delay-{input_topic}')
Can you be a bit more explicite?

2022-02-28 14:56 UTC, skovbakke commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +            group_id=f'delay-{input_topic}')
The first is a quite long line and the other is 4 short lines.  Regardless of what convention you are using for line lengths one of them is not following it. So it is inconsistent.

What convention are you following?

2022-03-01 14:41 UTC, jacobcrawford commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +            group_id=f'delay-{input_topic}')
Did not think of it :) I have changed the return on the get_input function.

2022-03-01 14:42 UTC, jacobcrawford commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +    return int(datetime.now().timestamp() * 1000)
Extracted to constant variable.

2022-03-03 12:01 UTC, jacobcrawford commented
Up for review again.

2022-03-03 12:48 UTC, skovbakke requested changes

2022-03-03 12:48 UTC, skovbakke commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +        ('DELAY_MS', 0)]
There is no need to use `\` when you are inside a list. Also, I prefer having the closing `]` on its own line.

2022-03-03 12:48 UTC, skovbakke commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +    return  (get_input_value(input_variable, default) for input_variable, default in INPUT_AND_DEFAULT)
Is there a framework we can use to handle input variables? Like a standard way of defining and parsing cli parameters, as well as declaring defaults?

2022-03-03 12:48 UTC, skovbakke commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +    return further_delay_ms
As I pointed out earlier; I think the calculations should be done using the python built-in datetime module.  This abstracts away the units and makes the function of the code easier to comprehend. 

Also the 7ish lines of code could be replaced by a single line of code (perhaps two).

2022-03-03 13:24 UTC, skovbakke commented on charts/kafka-topic-replicator/container/Dockerfile
> +RUN poetry install
```suggestion
COPY poetry.lock pyproject.toml ./
RUN poetry install
COPY app/* /app/
```
I think it makes sense to reorder these, that way you do not run poetry whenever the source code changes.

2022-03-03 13:34 UTC, skovbakke commented on charts/kafka-topic-replicator/container/Dockerfile
> +RUN poetry install
Perhaps we should add the `--no-dev` option to the install command.

2022-03-04 08:45 UTC, jacobcrawford commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +    return  (get_input_value(input_variable, default) for input_variable, default in INPUT_AND_DEFAULT)
hmm I have done a bit of research and I could not find a framework for handling input. 
I have made some changes to the input handling.

2022-03-04 10:56 UTC, jacobcrawford commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +    return further_delay_ms
Kafka timestamps are milliseconds since 1970. datetime timestamps are seconds since 1970, if using utc timezone. 
I have refactored the code and the test so that datetime is used, but I think the readability is worse.

2022-03-04 10:57 UTC, jacobcrawford commented
Up for review again.

2022-03-04 10:59 UTC, klausenbusk commented on charts/kafka-topic-replicator/container/pyproject.toml
> +authors = ["Your Name <you@example.com>"]
No author is better than non-real author or perhaps it should be `Team DT <team-dt@energinet.dk`. Thoughts?🤔 
```suggestion
authors = []
```

2022-03-04 10:59 UTC, klausenbusk commented on charts/kafka-topic-replicator/container/pyproject.toml
> +license = "MIT"
```suggestion
license = "Apache-2.0"
```

2022-03-07 07:24 UTC, jacobcrawford commented
Up for review again.

2022-03-07 07:27 UTC, klausenbusk commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +    return  (get_input_value(input_variable, default) for input_variable, default in INPUT_AND_DEFAULT)
I used https://docs.python.org/3/library/argparse.html for `syncctl`, but we pull the options from environment variabless in this case, which it doesn't support.

2022-03-07 07:57 UTC, skovbakke commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +            .add_errback(on_replication_fail)
What I was thinking would make it more readable, is something like this:

```suggestion
def calculate_delay(record_time: datetime.datetime, age: datetime.timedelta):
    """
    Calculate a delay, which is the time to wait until the record_time is older than age.    
    Args:
        record_time (datetime.datetime): The timestamp of the record.
        age (datetime.timedelta): The target age of the timestamp.

    Returns:
        datetime.timedelta: Time to wait until record is older than age.
    """ 
    return max(record_time+ age - datetime.now(tz=timezone.utc), timedelta(seconds=0))

def on_broker_acknowledge(record_metadata):
    log.info(f"Sucessfully replicated record: {record_metadata}")

def on_replication_fail(record_metadata):
    log.error(f"Failed to replcate record: {record_metadata}")

def start_replication(consumer, producer, output_topic: str, delay_ms: int):
    for record in consumer:
        # Kafka timestamps are UTC epoc in ms. 
        record_time = datetime.fromtimestamp(consumer_record.timestamp/MS_TO_SEC_FACTOR, tz=timezone.utc)
        time_until_replication = calculate_delay(record_time, timedelta(milliseconds=delay_ms))
        log.info(f"Sleeping for {time_until_replication.total_seconds()} milliseconds")
        sleep(time_until_replication.total_seconds())
        producer.send(output_topic, record.value) \
            .add_callback(on_broker_acknowledge) \
            .add_errback(on_replication_fail)
```

2022-03-07 08:30 UTC, klausenbusk commented
Could be fun to run `coverage` on this, to get code coverage: https://coverage.readthedocs.io/en/6.3.2/ :)

2022-03-07 08:32 UTC, klausenbusk commented on charts/kafka-topic-replicator/container/pyproject.toml
> +name = "kafka-topic-replicator"
Should we rename this to `Kafka Delayed Topic replicator` to more easy distinguish it from MirrorMaker?

2022-03-09 07:30 UTC, jacobcrawford commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +    return  (get_input_value(input_variable, default) for input_variable, default in INPUT_AND_DEFAULT)
i don't think it is worth it, to add more dependencies to this small application.

2022-03-09 07:33 UTC, jacobcrawford commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +            .add_errback(on_replication_fail)
I respectfully disagree :D

2022-03-09 07:35 UTC, jacobcrawford commented on charts/kafka-topic-replicator/container/pyproject.toml
> +name = "kafka-topic-replicator"
MirrorMaker is between clusters and this is internal. I don't think there is ground for confusion.

2022-03-10 07:16 UTC, skovbakke requested changes

2022-03-10 07:16 UTC, skovbakke commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +    time_delta = record_datetime + timedelta(milliseconds=delay_ms) - get_current_time()
Code does not work. `TypeError: can't subtract offset-naive and offset-aware datetimes`
Maybe add a test that ensures the code can run.

2022-03-10 08:28 UTC, jacobcrawford commented on charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
> +    time_delta = record_datetime + timedelta(milliseconds=delay_ms) - get_current_time()
I have ensured that the test mock is closer to the real implementation.

2022-03-10 08:58 UTC, skovbakke approved these changes
LGTM

2022-03-10 10:55 UTC, klausenbusk reviewed
To minor things, but looks good overall.

2022-03-10 10:55 UTC, klausenbusk commented on charts/kafka-topic-replicator/container/README.md
> +|  DELAY_MS | false |  0 | How long to delay the replication of a record. Counted from the timestamp of the input record  |
The spacing is very inconsistent.
```suggestion
| NAME | REQUIRED | DEFAULT | DESCRIPTION |
|---|---|---|---|
| KAFKA_BROKER_ENDPOINT | true  | None | The endpoint where the Kafka cluster can be reached |
| INPUT_TOPIC | true | None | The name of the topic to replicate |
| OUTPUT_TOPIC | true  | None | The name of the topic where the records will be replicated |
| DELAY_MS | false | 0 | How long to delay the replication of a record. Counted from the timestamp of the input record |
```

2022-03-10 10:55 UTC, klausenbusk commented on charts/kafka-topic-replicator/container/README.md
> +### Testing Building the application
```suggestion
### Testing the application
```

2022-03-10 13:55 UTC, merged

2022-03-10 13:55 UTC, jacobcrawford commented
I will merge this PR and ignore the latest comments, as we will never get anywhere with that kind of mentality. The requested changes do not way up for the cost of another peer review cycle.