kafka: Export topics to external cluster
distributed-technologies/helm-charts pull request #277
Opened 2022-03-02 10:52 UTC by skovbakke

Deploy kafka mirrormaker to sync the specified list of topics to the
target cluster. Nedded for integration with long term data storage
solution.

**Description of your changes:**

Checklist:

* [x] I have bumped the chart version
* [x] I have documented my changes if this is needed
* [x] I have described my changes in the "description of your changes" field
* [ ] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ ] I have created the necessary tests in the chart, if they are possible/necessary
* [x] I have squashed commits if necessary

2022-03-02 14:15 UTC, MadsHT submitted a review, later dismissed
LGTM

2022-03-02 14:16 UTC, klausenbusk commented on charts/kafka/chart/templates/kafka-mirrormaker.yaml
> +kind: KafkaMirrorMaker
Maybe we should use Mirror Maker 2.0 🤔

https://strimzi.io/docs/operators/latest/overview.html#bidirectional_replication_across_two_clusters

2022-03-02 14:16 UTC, klausenbusk commented on charts/kafka/chart/templates/kafka-mirrormaker.yaml
> +apiVersion: kafka.strimzi.io/v1beta2
```suggestion
# https://strimzi.io/docs/operators/latest/overview.html#example_yaml_showing_mirrormaker_configuration
apiVersion: kafka.strimzi.io/v1beta2
```
or for Mirror Maker 2.0:
```suggestion
# https://strimzi.io/docs/operators/latest/overview.html#example_yaml_showing_mirrormaker_2_0_configuration
apiVersion: kafka.strimzi.io/v1beta2
```

2022-03-10 14:42 UTC, skovbakke commented
I have changed the mirror maker instance to use MirrorMaker2.

2022-03-14 13:27 UTC, jacobcrawford requested changes
maybe we should set the replication factor to 2 instead of 1 wherever possible  so that we ensure  HA

2022-03-22 09:13 UTC, MadsHT commented
Have we tested that MM2 is working as intended?

2022-08-24 08:31 UTC, closed without merging