Feature/kafka default log retention
distributed-technologies/helm-charts pull request #279
Opened 2022-03-03 11:36 UTC by skovbakke

Checklist:

* [ ] I have bumped the chart version
* [ ] I have documented my changes if this is needed
* [ ] I have described my changes in the "description of your changes" field
* [ ] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ ] I have created the necessary tests in the chart, if they are possible/necessary
* [ ] I have squashed commits if necessary

2022-03-03 12:32 UTC, skovbakke commented
Ready for review

2022-03-03 12:34 UTC, klausenbusk submitted a review, later dismissed
LGTM 🎉

2022-03-04 07:16 UTC, jacobcrawford requested changes
Why are we setting these values in the helm chart and not in Yggdrasil?
Seems like cluster-specific configuration.

2022-03-04 12:57 UTC, skovbakke commented
> Why are we setting these values in the helm chart and not in Yggdrasil? Seems like cluster-specific configuration.

As I see it, this helm chart sets default values for our clusters, which can still be overwritten in yggdrasil. Singularity found that the current default (set in kafka to 7 days) was too long, and they ran out of storage.

We also set the configuration `auto.create.topic.enable: "false"`, which is different from the kafka default. If we should not change  default values here, why are we changing that one?

2022-03-04 13:05 UTC, MadsHT submitted a review, later dismissed
LGTM 

But should we have a talk about where we put what values, cause I feel like i've heard differing opinions on that topic?

2022-03-07 11:28 UTC, skovbakke commented
@jacobcrawford this could use attention 😊

2022-03-08 10:48 UTC, jacobcrawford commented
We set autoCreateTopic: false, because we have a general policy of IAC, so we do not want users to be able to create Kafka topics without specifying topics in code. The other values emerge from one specific environment.

2022-03-08 10:50 UTC, jacobcrawford commented
> 

We set autoCreateTopic: false, because we have a general policy of IAC, so we do not want users to be able to create Kafka topics without specifying topics in code. The other values emerge from one specific environment.

When we get hardware the values here are not relevant anymore, as we have a lot more resources. We should only set general values here and not environment-specific ones.

2022-03-09 09:33 UTC, skovbakke commented
The latest commit changes the behavior to what it was before, instead there is the option of setting the values for a deployment.

2022-03-09 09:46 UTC, MadsHT approved these changes
LGTM

2022-03-09 12:54 UTC, jacobcrawford approved these changes
LGTM

2022-03-09 13:39 UTC, merged