nidhogg: serviceMonitor for CNI
distributed-technologies/helm-charts pull request #285
Opened 2022-03-14 15:13 UTC by klausenbusk

**Description of your changes:**

Checklist:

* [ ] I have bumped the chart version
* [ ] I have documented my changes if this is needed
* [ ] I have described my changes in the "description of your changes" field
* [ ] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ ] I have created the necessary tests in the chart, if they are possible/necessary
* [ ] I have squashed commits if necessary

2022-03-14 15:27 UTC, MadsHT requested changes
Single request

2022-03-14 15:27 UTC, MadsHT commented on charts/nidhogg/chart/values.yaml
>  installCNI: true
Could we changes this now that we're making changes? 

```suggestion

cni:
  enabled: true
  serviceMonitor:
    enabled: false
```

2022-03-22 09:10 UTC, jacobcrawford approved these changes
LGTM

2022-03-22 09:11 UTC, MadsHT approved these changes
LGTM

2022-03-22 09:20 UTC, merged