Add to the halmchart that tenants can create kafka topics
distributed-technologies/helm-charts pull request #384
Opened 2022-10-21 12:51 UTC by jacobcrawford

**Description of your changes:**
Add to the helm chart that tenants can create Kafka topics and do some limited configuration

Documentation will come in a later task as it depends on the format in another user-story. 
Checklist:

* [x] I have bumped the chart version
* [ ] I have documented my changes if this is needed
* [x] I have described my changes in the "description of your changes" field
* [x] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ ] I have created the necessary tests in the chart, if they are possible/necessary
* [x] I have squashed commits if necessary

2022-10-25 07:12 UTC, jaxels10 requested changes
Just one comment

2022-10-26 11:45 UTC, klausenbusk commented
Please rebase to get https://github.com/distributed-technologies/helm-charts/pull/386, so the CI is green :)

2022-10-29 12:02 UTC, jacobcrawford commented on charts/tenant-base/chart/values.yaml
> +#      bytes: default -1
I have added new comments after looking at the Grafana charts

2022-10-30 08:41 UTC, jaxels10 approved these changes
This LGTM

2022-10-30 08:41 UTC, merged