tenant-base: Implemented possibility to mount configmaps as environment variables
distributed-technologies/helm-charts pull request #407
Opened 2022-11-28 07:13 UTC by jaxels10

**Description of your changes:**
I have added the possibility for our tenants to mount a configmap as environment variables in a pod. This is done to make it easier for tenants to use environment variables in their pods and easier for them to understand how to mount them.

Checklist:

* [x] I have bumped the chart version
* [x] I have documented my changes if this is needed
* [x] I have described my changes in the "description of your changes" field
* [x] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [x] I have created the necessary tests in the chart, if they are possible/necessary
* [x] I have squashed commits if necessary

2022-11-28 13:17 UTC, nashton requested changes

2022-11-28 13:17 UTC, nashton commented on charts/tenant-base/chart/templates/deployment.yaml
> +          {{- end }}
Same as above:
```suggestion
          {{- range .configMaps }}
          - configMapRef:
              name: {{ printf "%s-%s" $name .name }}
          {{- end }}
```

2022-11-28 13:17 UTC, nashton commented on charts/tenant-base/chart/templates/deployment.yaml
>            {{- end }}
If I understand Helm templates correct, the following is equivalent and more concise:
```suggestion
          {{- range .secrets }}
          - secretRef:
              name: {{ printf "%s-%s" (include "chart.fullname" $) $name }}
          {{- end }}
```

2022-11-29 09:19 UTC, jaxels10 commented on charts/tenant-base/chart/templates/deployment.yaml
> +          {{- end }}
I have changed this now :)

2022-11-29 09:26 UTC, nashton approved these changes

2022-11-29 09:26 UTC, merged