Ensure pods are redeployed on configmap update
distributed-technologies/helm-charts pull request #412
Opened 2022-12-08 10:21 UTC by jacobcrawford

**Description of your changes:**
We need to ensure that the pods of a deployment is redeployed on configmap updates.

Checklist:

* [x] I have bumped the chart version
* [x] I have documented my changes if this is needed
* [x] I have described my changes in the "description of your changes" field
* [ ] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ ] I have created the necessary tests in the chart, if they are possible/necessary
* [x] I have squashed commits if necessary

2022-12-08 10:47 UTC, MadsHT requested changes
Feedback :)

2022-12-08 10:47 UTC, MadsHT commented on charts/tenant-base/chart/templates/deployment.yaml
> +        checksum/config: |
I am not sure having a multiline checksum would work. besides reading [helm/helm#3418](https://github.com/helm/helm/issues/3418) it sounds like having multiple `check/<config-name>` annotations is "best pratice" but this is not documented anywhere.. :P

2022-12-08 10:47 UTC, MadsHT commented on charts/tenant-base/chart/templates/deployment.yaml
>        {{- end }}
This value is not used and I think we should just remove it..

```suggestion

```

2022-12-08 12:54 UTC, jacobcrawford commented on charts/tenant-base/chart/templates/deployment.yaml
> +        checksum/config: |
Good idea!

2022-12-08 13:04 UTC, jacobcrawford commented on charts/tenant-base/chart/templates/deployment.yaml
> +        checksum/config: |
![image](https://user-images.githubusercontent.com/22328547/206453741-b9f54a4e-457d-4d41-b5b8-4a1a2ab65e47.png)

2022-12-08 13:36 UTC, MadsHT reviewed
Small suggestion :)

2022-12-08 14:12 UTC, jacobcrawford commented on charts/tenant-base/chart/templates/deployment.yaml
> +                {{- $allConfigMap | toYaml | toString | sha256sum | nindent 10}}
![image](https://user-images.githubusercontent.com/22328547/206468087-816a7252-48e6-4e11-80a6-f1a52d4bf3f7.png)

2022-12-09 07:53 UTC, MadsHT commented on charts/tenant-base/chart/templates/deployment.yaml
> +                {{- printf "%s/%s: %s" "checksum/configmap" $allConfigMap.name ($allConfigMap | toYaml | toString | sha256sum) | nindent 8 }}
I am sorry, my suggestion was slightly off, we do not need the `configmap` that should represent the name of the configmap.. sorry :/
```suggestion
                {{- printf "%s/%s: %s" "checksum" $allConfigMap.name ($allConfigMap | toYaml | toString | sha256sum) | nindent 8 }}
```

2022-12-13 07:02 UTC, jacobcrawford commented on charts/tenant-base/chart/templates/deployment.yaml
> +                {{- printf "%s/%s: %s" "checksum/configmap" $allConfigMap.name ($allConfigMap | toYaml | toString | sha256sum) | nindent 8 }}
Well, I still think that the "configmap" string should remain so that we know the type of object that created the checksum. If we at some point do the same with secrets it would be nice to be able to tell the difference.
In general i think more descriptive naming is always prefered.

2022-12-13 07:31 UTC, MadsHT commented on charts/tenant-base/chart/templates/deployment.yaml
> +                {{- printf "%s/%s: %s" "checksum/configmap" $allConfigMap.name ($allConfigMap | toYaml | toString | sha256sum) | nindent 8 }}
That is a fair point (y)

2022-12-13 07:31 UTC, MadsHT approved these changes

2022-12-13 07:51 UTC, merged