Remove labels from network policies
distributed-technologies/helm-charts pull request #414
Opened 2023-01-01 19:58 UTC by jaxels10

**Description of your changes:**
We do not want our users to deal with labels in the network policies as this subject is already complicated enough as is. They now have to deal with release name and deployment name instead.

Checklist:

* [x] I have bumped the chart version
* [x] I have documented my changes if this is needed
* [x] I have described my changes in the "description of your changes" field
* [x] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ ] I have created the necessary tests in the chart, if they are possible/necessary
* [x] I have squashed commits if necessary

2023-01-01 19:59 UTC, jaxels10 commented
I would like some help with this PR from @MadsHT to do the labels correctly. Right now they are mainly added as a new line and not under the _helpers functions.
I am also in doubt whether or not the ingress ports need to be a list, but lets discuss

2023-01-02 10:53 UTC, jaxels10 commented
This was tested with 2 pods from different deployments. First I tried to curl from one pod to the other without any network policies and it was denied:
![image](https://user-images.githubusercontent.com/43172501/210221855-2999644c-8ebb-4939-883f-d94a14838da9.png)
Then, I tried adding an allowed connection through ingress and egress rules:
![image](https://user-images.githubusercontent.com/43172501/210221900-4e00e8a7-33e2-4818-84e0-0a11c975982b.png)
![image](https://user-images.githubusercontent.com/43172501/210221916-86b17e91-0f4e-4bcb-b475-81fac1f10646.png)
This solved the issue:
![image](https://user-images.githubusercontent.com/43172501/210221963-7f4cfbaa-5cba-4ec5-9dfe-8fb0693b29c3.png)

2023-01-02 10:58 UTC, MadsHT requested changes
Semantics, otherwise looks good 👍

2023-01-02 10:58 UTC, MadsHT commented on charts/tenant-base/docs/deployment.md
> +This allows incoming traffic(ingress) to the pod from pods in the dlr helm release that is under the dlr-data deployment. This is done on port http, which is defined under `ports`.
```suggestion
This allows incoming traffic(ingress) to the pod from pods in the dlr helm release that is under the 'data' deployment. This is done on port http, which is defined under `ports`.
```

2023-01-02 10:58 UTC, MadsHT commented on charts/tenant-base/docs/deployment.md
> +This also allows outgoing traffic(egress) from the pod to pods in the same dkr-data deployment under the dlr helm release on port `8080/TCP`.
```suggestion
This also allows outgoing traffic(egress) from the pod to pods in the same 'data' deployment under the dlr helm release on port `8080/TCP`.
```

2023-01-02 11:26 UTC, jaxels10 commented on charts/tenant-base/docs/deployment.md
> +This allows incoming traffic(ingress) to the pod from pods in the dlr helm release that is under the dlr-data deployment. This is done on port http, which is defined under `ports`.
Changed

2023-01-02 11:26 UTC, jaxels10 commented on charts/tenant-base/docs/deployment.md
> +This also allows outgoing traffic(egress) from the pod to pods in the same dkr-data deployment under the dlr helm release on port `8080/TCP`.
Changed

2023-01-02 11:31 UTC, MadsHT approved these changes
LGTM

2023-01-02 11:32 UTC, merged