Feature/update docs
distributed-technologies/helm-charts pull request #421
Opened 2023-02-16 10:20 UTC by jaxels10

**Description of your changes:**
I have re-written the entire documentation for this helm chart, so that it has a better flow and will be easier to understand for our users.

Checklist:

* [x] I have bumped the chart version
* [x] I have documented my changes if this is needed
* [x] I have described my changes in the "description of your changes" field
* [ ] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [x] I have created the necessary tests in the chart, if they are possible/necessary
* [x] I have squashed commits if necessary

2023-02-16 13:37 UTC, jacobcrawford requested changes
A few comments.

2023-02-16 13:37 UTC, jacobcrawford commented on charts/tenant-base/chart/README.md
> +Please refer to the [documentation here](../docs/documentation.md).
I think we should delete this and extract the document further down. See comment below.

2023-02-16 13:37 UTC, jacobcrawford commented on charts/tenant-base/chart/README.md
> +## Configuration
We should somehow show that the configurations are not only for the **podinfo** key. E.g. by writing the parameter as **deployments.\<application-name\>.image**

2023-02-16 13:37 UTC, jacobcrawford commented on charts/tenant-base/chart/README.md
> +The chart is made in a way that allows for creation of a number of resources using only the [values.yaml](./chart/values.yaml) file.
I think we should delete this whole section down to the **Configuration** section and extract the **Documentation** document here instead.

Seems like the same information is here two times and the **Documentation** document explains ways better what happens.

2023-02-16 13:54 UTC, jaxels10 commented on charts/tenant-base/chart/README.md
> +## Configuration
I agree, I have done these changes

2023-02-16 13:55 UTC, jaxels10 commented on charts/tenant-base/chart/README.md
> +The chart is made in a way that allows for creation of a number of resources using only the [values.yaml](./chart/values.yaml) file.
I agree, I have done these changes

2023-02-20 09:58 UTC, dueruen commented on charts/tenant-base/docs/kafkatopic.md
> +    - name: "example-topic"
Is it a requirement that this name is the same as the topic name? If so maybe specify that.

2023-02-20 09:58 UTC, dueruen commented on charts/tenant-base/docs/kafkatopic.md
> +This example creates a kafka topic called `example-topic` with 3 replicas, 1 partition and a retention rate of 1 week and no byte retention. The example also give access to the created kafka topic fo
Isn't it creating a topic called `tenant-test-example-topic`?

2023-02-20 09:58 UTC, dueruen commented on charts/tenant-base/docs/kafkatopic.md
> +This example creates a kafka topic called `example-topic` with 3 replicas, 1 partition and a retention rate of 1 week and no byte retention. The example also give access to the created kafka topic fo
Is the access control fix? Or is it still needed to have produce and consume as true then having multiple accesses?

2023-02-27 14:37 UTC, nashton requested changes

2023-02-28 08:13 UTC, jaxels10 commented on charts/tenant-base/docs/kafkatopic.md
> +This example creates a kafka topic called `example-topic` with 3 replicas, 1 partition and a retention rate of 1 week and no byte retention. The example also give access to the created kafka topic fo
@dueruen I would have to ask you to contact Jacob and ask him, I am not aware of this issue. Is this something that should stop this PR from being merged? If not, let's just resolve the comment

2023-02-28 08:15 UTC, jaxels10 commented on charts/tenant-base/docs/kafkatopic.md
> +This example creates a kafka topic called `example-topic` with 3 replicas, 1 partition and a retention rate of 1 week and no byte retention. The example also give access to the created kafka topic fo
@dueruen I think you are right about that. We have previously talked about abstracting this away from the user, so you only have to think about the kafka topic name and not the prefix. I will get back to you on this soon

2023-03-01 08:59 UTC, nashton submitted a review, later dismissed

2023-03-06 13:58 UTC, jacobcrawford reviewed
Answered a few questions!

2023-03-07 06:51 UTC, jacobcrawford commented on charts/tenant-base/docs/kafkatopic.md
> +    - name: "example-topic"
Do you mean that one should specify the namespace prefix or not?

2023-03-07 08:02 UTC, jaxels10 commented on charts/tenant-base/chart/README.md
> +Secrets are a way to store sensitive information in Kubernetes. This could be tokens, passwords or certificates. To learn how to create a secret, please see [this document](../docs/secret.md).
Agreed, removed this from each of them

2023-03-07 08:16 UTC, jaxels10 commented on charts/tenant-base/docs/kafkatopic.md
> +This example creates a kafka topic called `example-topic` with 3 replicas, 1 partition and a retention rate of 1 week and no byte retention. The example also give access to the created kafka topic fo
I have specified this in the new commit

2023-03-07 08:16 UTC, jaxels10 commented on charts/tenant-base/docs/kafkatopic.md
> +This example creates a kafka topic called `example-topic` with 3 replicas, 1 partition and a retention rate of 1 week and no byte retention. The example also give access to the created kafka topic fo
I have made this clear in the newest commit

2023-03-07 08:56 UTC, jaxels10 commented on charts/tenant-base/docs/kafkatopic.md
> +    - name: "example-topic"
I have specified this in the newest changes

2023-03-07 11:25 UTC, jacobcrawford approved these changes
LGTM

2023-03-07 11:30 UTC, merged