removed ceph, from helm_chart
distributed-technologies/helm-charts pull request #442
Opened 2023-08-29 10:39 UTC by luciosis

**Description of your changes:**

Checklist:

PR Author:

* [ ] I have bumped the chart version
* [ ] If necessary, I have documented my changes
* [ ] If writing a guide I have followed it my self
* [ ] I have described my changes in the "description of your changes" field
* [ ] I have tested (and noted how) this change on a running cluster by deploying a new cluster with the PR branch
* [ ] I have tested (and noted how) this change on a running cluster by migrating from the master branch to the PR branch and pasted the results in the comments
* [ ] If possible, automatic tests have been created for the change
* [ ] My commit messages describe why, not how
* [ ] I have linked my PR to a task and dragged it into the peer review column

PR Reviewer:

* [ ] I have understood why this PR exists
* [ ] I have given thought to, whether this is the best solution for the problem
* [ ] If my suggestions further expand the scope of the task, it should be suggested in the PR, but created as a separate task
* [ ] After reviewing I have dragged the task into the implement feedback column
* [ ] I encourage developers to simplify code or add code comments instead of just explaining the complexity to me

2023-08-29 10:44 UTC, RolfTherkildsenAtWork approved these changes

2023-08-31 22:00 UTC, jaxels10 requested changes
We need to write in the changelog what the change is so our tenants can upgrade with a positive mind

2023-09-04 05:55 UTC, jaxels10 reviewed
Just one small change before approving :)

2023-09-04 05:55 UTC, jaxels10 commented on charts/tenant-base/chart/README.md
> +- Sets the default PVC storageclassname to "". This enforces pvc's storageclasses to be default storageclass. This change does not affect tenants.
```suggestion
- Sets the PVC storageclassname to "". This enforces pvc's storageclasses to be the default storageclass on the cluster. This change does not affect tenants, however, if they want to use a PVC they must upgrade to this version.
```

2023-09-04 09:01 UTC, jaxels10 approved these changes
LGTM

2023-09-04 09:10 UTC, merged