Added an entry to the README on how to add a helm chart to the mono repo
distributed-technologies/helm-charts pull request #53
Opened 2021-11-09 08:40 UTC by jaxels10

**Description of your changes:**
Added an entry to the README on how to add a helm chart to the mono repo

Checklist:

* [ ] I have bumped the chart version
* [x] I have documented my changes if this is needed
* [x] I have described my changes in the "description of your changes" field
* [ ] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ ] I have created the necessary tests in the chart, if they are possible/necessary
* [ ] I have squashed commits if necessary

2021-11-09 08:42 UTC, skovbakke commented
@jacobcrawford should be testing this very soon

2021-11-09 13:14 UTC, jacobcrawford requested changes
Nothing much.

2021-11-09 13:14 UTC, jacobcrawford commented on README.md
> +3. It is important that you have a values.yaml file, even if it is empty, since the linter will otherwise fail
I think we should also have a README.md file to describe the chart.

2021-11-10 09:24 UTC, jaxels10 commented on README.md
> +3. It is important that you have a values.yaml file, even if it is empty, since the linter will otherwise fail
I have now added this and when the workflows are (hopefully) passed, it is ready for re-review :)

2021-11-10 17:00 UTC, jacobcrawford approved these changes
LGTM

2021-11-11 07:08 UTC, merged