Feature/forward proxy and web server
distributed-technologies/helm-charts pull request #71
Opened 2021-11-10 11:23 UTC by skovbakke

**Description of your changes:**

Checklist:

* [ ] I have bumped the chart version
* [ ] I have documented my changes if this is needed
* [ ] I have described my changes in the "description of your changes" field
* [ ] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ ] I have created the necessary tests in the chart, if they are possible/necessary
* [ ] I have squashed commits if necessary

2021-11-17 17:37 UTC, jacobcrawford requested changes
Seems like the pod is killed by its own livenessprobe before it fully starts up. A delay or longer intervals might fix this:
![image](https://user-images.githubusercontent.com/22328547/142252698-40088063-5aba-4cc1-a25f-0b75cf4a60fc.png)

2021-11-17 17:37 UTC, jacobcrawford commented on charts/fwd-proxy/chart/templates/configmap-example-html.yaml
> +apiVersion: v1
Is this file unused?

2021-11-17 17:37 UTC, jacobcrawford commented on charts/fwd-proxy/chart/config/demo.yaml
> +static_resources:
Is this file unused?

2021-11-17 17:37 UTC, jacobcrawford commented on charts/fwd-proxy/chart/test/example.html
> +<!DOCTYPE html>
is this file unused?

2021-11-17 17:42 UTC, klausenbusk commented
> Seems like the pod is killed by its own livenessprobe before it fully starts up. A delay or longer intervals might fix this:

The service has a hard requirement on the artifact-service and git-service. Was they running when you tested?

2021-11-17 18:07 UTC, skovbakke commented
![image](https://user-images.githubusercontent.com/78202835/142257231-3691d7d0-14c9-459f-a631-9a2aa9ec19ce.png)
Cannot reproduce the failure @jacobcrawford. It works as expected.

2021-11-19 11:12 UTC, jacobcrawford commented
> > Seems like the pod is killed by its own livenessprobe before it fully starts up. A delay or longer intervals might fix this:
> 
> The service has a hard requirement on the artifact-service and git-service. Was they running when you tested?

If there is a hard requirement it should be documented in the README, else the char should be able to be deployed by itself?

2021-11-23 06:26 UTC, jacobcrawford approved these changes
LGTM. Unless you wanted to squash the commits further, this is ready for merge :)

2021-11-23 07:19 UTC, merged